/*
  Practica 2 - Jenkinsfile dummy (PUNTO DE PARTIDA)

  Este Jenkinsfile es intencionalmente simple. En la Practica 2 iras anadiendo
  piezas (stages, agents, funciones Groovy, Docker build, docker compose, etc.)
  hasta construir un pipeline CI/CD completo.
*/
// ========================= 
// Función reutilizable (Ejercicio 4) 
// ========================= 
def runInDocker(String image, Closure body) { 
  docker.image(image).inside { 
    body() 
  } 
}


pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    // =========================
    // Ejercicio 3: construir imagen CI con Dockerfile 
    // ========================= 
    stage('CI - Build tools image') { 
    steps { script { 
      // Construimos la imagen de CI desde devops/ci.Dockerfile 
      env.CI_IMAGE_NAME = "java-ci-tools:${env.BUILD_NUMBER}" 
      docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .") 
    } 
          } 
    } 
    // ========================= 
    //    Ejercicio 3: Lint sin runInDocker
    // =========================
    stage('CI - Lint') { 
    // agent { 
       //docker { 
      //    image "${env.CI_IMAGE_NAME}" 
        //  reuseNode true
        //  } 
    //  } 
      steps {
        //sh 'make lint'
       script {
         runInDocker(env.CI_IMAGE_NAME) {
           sh 'make lint' 
         } 
       }
      } 
    }
    // ========================= 
    // Ejercicio 3: Test sin runInDocker 
    // ========================= 
    stage('CI - Test') { 
     // agent { 
      //  docker { 
        //  image "${env.CI_IMAGE_NAME}" 
        //  reuseNode true 
     //   } 
     // } 
      steps { 
         script { 
           runInDocker(env.CI_IMAGE_NAME) {
        sh 'make test' 
           }
         }
      }
    }
    stage('Test') {
      /*
        `agent` dentro de un stage permite que SOLO ese stage se ejecute en un contexto concreto.
        En este caso, usamos Docker como capa de virtualizacion: los comandos se ejecutan dentro
        de un contenedor temporal.
      */
      agent {
        docker {
          image 'maven:3.8.6-openjdk-11-slim'
        }
      }
      steps {
        sh 'mvn -version'
        sh 'echo "Stage dummy. En la Practica 2 ejecutaras aqui los tests unitarios."'
      }
    }
       stage('Info') {
            steps { 
                echo "Job: ${env.JOB_NAME}"
                echo "Build ${env.BUILD_NUMBER}"
            }
        }
  }
}
